"""initial schema from production

Revision ID: 0b70fd51f30c
Revises: 
Create Date: 2026-02-25 16:38:13.495208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b70fd51f30c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_unique_constraint(None, 'categories', ['name'])
    op.alter_column('goals', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=True)
    op.alter_column('goals', 'target_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('goals', 'deadline',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_foreign_key(None, 'goals', 'accounts', ['account_id'], ['id'])
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.alter_column('recurring_transactions', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=True)
    op.alter_column('recurring_transactions', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('recurring_transactions', 'day_of_month',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_recurring_transactions_id'), 'recurring_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'accounts', ['target_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_recurring_transactions_id'), table_name='recurring_transactions')
    op.alter_column('recurring_transactions', 'day_of_month',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('recurring_transactions', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('recurring_transactions', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=False)
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.alter_column('goals', 'deadline',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('goals', 'target_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('goals', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=100),
               nullable=False)
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    # ### end Alembic commands ###
